# Generated by Django 5.0.6 on 2026-06-30 11:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('name', models.CharField(max_length=160, verbose_name='اسم الصندوق')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الرصيد الافتتاحي')),
                ('currency', models.CharField(default='JOD', max_length=10, verbose_name='العملة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'صندوق نقد',
                'verbose_name_plural': 'الصناديق النقدية',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('name', models.CharField(max_length=160, verbose_name='اسم العميل')),
                ('phone', models.CharField(db_index=True, max_length=40, verbose_name='رقم الهاتف')),
                ('secondary_phone', models.CharField(blank=True, max_length=40, verbose_name='رقم إضافي')),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='المدينة')),
                ('area', models.CharField(blank=True, max_length=100, verbose_name='المنطقة')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('source', models.CharField(blank=True, help_text='Facebook / Instagram / Referral / Website', max_length=100, verbose_name='مصدر العميل')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='وسوم')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('name', models.CharField(max_length=160, verbose_name='اسم شركة التوصيل')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='هاتف الشركة')),
                ('default_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='أجرة التوصيل الافتراضية')),
                ('tracking_url_template', models.CharField(blank=True, help_text='استخدم {tracking} داخل الرابط', max_length=255, verbose_name='رابط التتبع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'شركة توصيل',
                'verbose_name_plural': 'شركات التوصيل',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='رمز المنتج')),
                ('name', models.CharField(max_length=160, verbose_name='اسم المنتج')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='التصنيف')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر البيع')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تكلفة المنتج')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية الحالية')),
                ('low_stock_alert', models.PositiveIntegerField(default=5, verbose_name='حد التنبيه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('action', models.CharField(max_length=120, verbose_name='الإجراء')),
                ('model_name', models.CharField(blank=True, max_length=120, verbose_name='الشاشة')),
                ('object_id', models.CharField(blank=True, max_length=120, verbose_name='رقم السجل')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل حركة',
                'verbose_name_plural': 'سجل الحركات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('category', models.CharField(choices=[('ads', 'إعلانات'), ('delivery', 'توصيل'), ('salary', 'رواتب'), ('rent', 'إيجار'), ('supplies', 'مستلزمات'), ('other', 'أخرى')], max_length=30, verbose_name='التصنيف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('description', models.CharField(max_length=255, verbose_name='البيان')),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('cashbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cashbox', verbose_name='الصندوق')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصاريف',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر الوحدة')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='خصم')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='أجرة التوصيل')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('confirmed', 'مؤكد'), ('preparing', 'قيد التجهيز'), ('with_delivery', 'مع التوصيل'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغي'), ('returned', 'راجع')], db_index=True, default='new', max_length=30, verbose_name='حالة الطلب')),
                ('payment_status', models.CharField(choices=[('unpaid', 'غير مدفوع'), ('partial', 'مدفوع جزئياً'), ('paid', 'مدفوع بالكامل'), ('refunded', 'مسترد')], db_index=True, default='unpaid', max_length=30, verbose_name='حالة الدفع')),
                ('priority', models.CharField(choices=[('normal', 'عادي'), ('high', 'مهم'), ('urgent', 'عاجل')], default='normal', max_length=20, verbose_name='الأولوية')),
                ('delivery_tracking_number', models.CharField(blank=True, max_length=120, verbose_name='رقم التتبع')),
                ('order_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='تاريخ الطلب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف المسؤول')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.customer', verbose_name='العميل')),
                ('delivery_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.deliverycompany', verbose_name='شركة التوصيل')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-order_date'],
                'permissions': [('can_view_reports', 'Can view advanced reports')],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('result', models.CharField(choices=[('call_later', 'الاتصال لاحقاً'), ('confirmed', 'تم التأكيد'), ('no_answer', 'لا يوجد رد'), ('cancelled', 'تم الإلغاء'), ('complaint', 'شكوى'), ('note', 'ملاحظة'), ('upsell', 'فرصة بيع إضافية')], max_length=30, verbose_name='نتيجة المتابعة')),
                ('note', models.TextField(verbose_name='تفاصيل المتابعة')),
                ('next_followup_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='موعد المتابعة القادمة')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف المسؤول')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='core.customer', verbose_name='العميل')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='core.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'متابعة',
                'verbose_name_plural': 'المتابعات',
                'ordering': ['next_followup_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('method', models.CharField(choices=[('cash', 'نقدي'), ('cliq', 'كليك'), ('bank', 'تحويل بنكي'), ('card', 'بطاقة'), ('delivery', 'تحصيل من شركة التوصيل')], default='cash', max_length=30, verbose_name='طريقة الدفع')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الدفع')),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='مرجع العملية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('cashbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cashbox', verbose_name='الصندوق')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('transaction_type', models.CharField(choices=[('in', 'قبض'), ('out', 'صرف')], max_length=10, verbose_name='نوع الحركة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('description', models.CharField(max_length=255, verbose_name='البيان')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('cashbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.cashbox', verbose_name='الصندوق')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.payment')),
            ],
            options={
                'verbose_name': 'حركة صندوق',
                'verbose_name_plural': 'حركات الصناديق',
                'ordering': ['-date'],
            },
        ),
    ]
