# Generated by Django 5.0.6 on 2026-06-30 12:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('name', models.CharField(max_length=160, verbose_name='اسم الصندوق')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الرصيد الافتتاحي')),
                ('currency', models.CharField(default='JOD', max_length=10, verbose_name='العملة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'صندوق نقد',
                'verbose_name_plural': 'الصناديق النقدية',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('name', models.CharField(max_length=160, verbose_name='اسم العميل/الجهة')),
                ('phone', models.CharField(db_index=True, max_length=40, verbose_name='رقم الهاتف')),
                ('secondary_phone', models.CharField(blank=True, max_length=40, verbose_name='رقم إضافي')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='المدينة')),
                ('area', models.CharField(blank=True, max_length=100, verbose_name='المنطقة')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('source', models.CharField(blank=True, help_text='Facebook / Instagram / Referral / Website / WhatsApp', max_length=100, verbose_name='مصدر العميل')),
                ('grade', models.CharField(choices=[('A', 'A - مهم جداً'), ('B', 'B - جيد'), ('C', 'C - عادي'), ('D', 'D - ضعيف')], default='B', max_length=5, verbose_name='تصنيف العميل')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='وسوم')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('last_contact_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر تواصل')),
                ('next_action_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='موعد الإجراء القادم')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('name', models.CharField(max_length=160, verbose_name='اسم شركة التوصيل/الشريك')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='هاتف الشركة')),
                ('default_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الأجرة الافتراضية')),
                ('tracking_url_template', models.CharField(blank=True, help_text='استخدم {tracking} داخل الرابط', max_length=255, verbose_name='رابط التتبع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'شركة/شريك',
                'verbose_name_plural': 'الشركات والشركاء',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='رمز المنتج/الخدمة')),
                ('name', models.CharField(max_length=160, verbose_name='اسم المنتج/الخدمة')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='التصنيف')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر البيع')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='التكلفة')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية الحالية')),
                ('low_stock_alert', models.PositiveIntegerField(default=5, verbose_name='حد التنبيه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'منتج/خدمة',
                'verbose_name_plural': 'المنتجات/الخدمات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('action', models.CharField(max_length=120, verbose_name='الإجراء')),
                ('model_name', models.CharField(blank=True, max_length=120, verbose_name='الشاشة')),
                ('object_id', models.CharField(blank=True, max_length=120, verbose_name='رقم السجل')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل حركة',
                'verbose_name_plural': 'سجل الحركات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('category', models.CharField(choices=[('ads', 'إعلانات'), ('delivery', 'توصيل'), ('salary', 'رواتب'), ('rent', 'إيجار'), ('supplies', 'مستلزمات'), ('software', 'برمجيات'), ('other', 'أخرى')], max_length=30, verbose_name='التصنيف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('description', models.CharField(max_length=255, verbose_name='البيان')),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('cashbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cashbox', verbose_name='الصندوق')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصاريف',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر الوحدة')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='خصم')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='أجرة/تكلفة إضافية')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('confirmed', 'مؤكد'), ('preparing', 'قيد التجهيز'), ('with_delivery', 'مع التوصيل'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغي'), ('returned', 'راجع'), ('waiting', 'بانتظار رد'), ('closed', 'مغلق')], db_index=True, default='new', max_length=30, verbose_name='حالة الطلب/المعاملة')),
                ('payment_status', models.CharField(choices=[('unpaid', 'غير مدفوع'), ('partial', 'مدفوع جزئياً'), ('paid', 'مدفوع بالكامل'), ('refunded', 'مسترد')], db_index=True, default='unpaid', max_length=30, verbose_name='حالة الدفع')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('normal', 'عادي'), ('high', 'مهم'), ('urgent', 'عاجل')], default='normal', max_length=20, verbose_name='الأولوية')),
                ('delivery_tracking_number', models.CharField(blank=True, max_length=120, verbose_name='رقم التتبع/المرجع')),
                ('order_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='تاريخ الطلب/المعاملة')),
                ('due_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.customer', verbose_name='العميل')),
                ('delivery_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.deliverycompany', verbose_name='شركة/شريك')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.product', verbose_name='المنتج/الخدمة')),
            ],
            options={
                'verbose_name': 'طلب/معاملة',
                'verbose_name_plural': 'الطلبات/المعاملات',
                'ordering': ['-order_date'],
                'permissions': [('can_view_reports', 'Can view advanced reports')],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('title', models.CharField(blank=True, max_length=180, verbose_name='العنوان')),
                ('body', models.TextField(verbose_name='الملاحظة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quick_notes', to='core.customer', verbose_name='العميل')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quick_notes', to='core.order', verbose_name='الطلب/المعاملة')),
            ],
            options={
                'verbose_name': 'ملاحظة',
                'verbose_name_plural': 'الملاحظات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('result', models.CharField(choices=[('call_later', 'الاتصال لاحقاً'), ('confirmed', 'تم التأكيد'), ('no_answer', 'لا يوجد رد'), ('cancelled', 'تم الإلغاء'), ('complaint', 'شكوى'), ('note', 'ملاحظة'), ('upsell', 'فرصة بيع إضافية'), ('done', 'تم الإنجاز')], max_length=30, verbose_name='نتيجة المتابعة')),
                ('note', models.TextField(verbose_name='تفاصيل المتابعة')),
                ('next_followup_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='موعد المتابعة القادمة')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='core.customer', verbose_name='العميل')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='core.order', verbose_name='الطلب/المعاملة')),
            ],
            options={
                'verbose_name': 'متابعة',
                'verbose_name_plural': 'المتابعات',
                'ordering': ['next_followup_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/', verbose_name='الملف')),
                ('title', models.CharField(blank=True, max_length=180, verbose_name='اسم الملف')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.customer', verbose_name='العميل')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.order', verbose_name='الطلب/المعاملة')),
            ],
            options={
                'verbose_name': 'ملف مرفق',
                'verbose_name_plural': 'الملفات المرفقة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('method', models.CharField(choices=[('cash', 'نقدي'), ('cliq', 'كليك'), ('bank', 'تحويل بنكي'), ('card', 'بطاقة'), ('delivery', 'تحصيل من شركة التوصيل'), ('other', 'أخرى')], default='cash', max_length=30, verbose_name='طريقة الدفع')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الدفع')),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='مرجع العملية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('cashbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cashbox', verbose_name='الصندوق')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.order', verbose_name='الطلب/المعاملة')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('transaction_type', models.CharField(choices=[('in', 'قبض'), ('out', 'صرف')], max_length=10, verbose_name='نوع الحركة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('description', models.CharField(max_length=255, verbose_name='البيان')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('cashbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.cashbox', verbose_name='الصندوق')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.payment')),
            ],
            options={
                'verbose_name': 'حركة صندوق',
                'verbose_name_plural': 'حركات الصناديق',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('title', models.CharField(max_length=180, verbose_name='المهمة')),
                ('description', models.TextField(blank=True, verbose_name='التفاصيل')),
                ('due_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='تاريخ التنفيذ')),
                ('status', models.CharField(choices=[('todo', 'مطلوب'), ('doing', 'قيد العمل'), ('done', 'منجز'), ('cancelled', 'ملغي')], db_index=True, default='todo', max_length=20, verbose_name='الحالة')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('normal', 'عادي'), ('high', 'مهم'), ('urgent', 'عاجل')], default='normal', max_length=20, verbose_name='الأولوية')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.customer', verbose_name='العميل')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.order', verbose_name='الطلب/المعاملة')),
            ],
            options={
                'verbose_name': 'مهمة',
                'verbose_name_plural': 'المهام',
                'ordering': ['status', 'due_date', '-priority'],
            },
        ),
    ]
