# Generated by Django 5.0.6 on 2026-07-01 12:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_repair_existing_render_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'جديد'), ('confirmed', 'مؤكد'), ('preparing', 'قيد التجهيز'), ('with_delivery', 'مع التوصيل'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغي'), ('rejected', 'مرفوض'), ('no_answer', 'لم يتم الرد على الهاتف'), ('returned', 'راجع'), ('waiting', 'بانتظار رد'), ('closed', 'مغلق')], db_index=True, default='new', max_length=30, verbose_name='حالة الطلب/المعاملة'),
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('movement_type', models.CharField(choices=[('in', 'إدخال للمستودع'), ('out', 'تسليم/خروج'), ('return', 'مرتجع'), ('adjust', 'تسوية جرد'), ('damaged', 'تالف')], db_index=True, max_length=20, verbose_name='نوع الحركة')),
                ('quantity', models.IntegerField(verbose_name='الكمية')),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='تاريخ الحركة')),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='مرجع/رقم فاتورة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='core.order', verbose_name='الأوردر المرتبط')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='core.product', verbose_name='المادة/المنتج')),
            ],
            options={
                'verbose_name': 'حركة مستودع',
                'verbose_name_plural': 'حركات المستودع',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ReturnRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية الراجعة')),
                ('reason', models.CharField(choices=[('customer', 'رفض/إرجاع من العميل'), ('damaged', 'تالف'), ('wrong', 'منتج خاطئ'), ('exchange', 'استبدال'), ('other', 'أخرى')], default='customer', max_length=30, verbose_name='سبب المرتجع')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مبلغ مسترد للعميل')),
                ('returned_to_stock', models.BooleanField(default=True, verbose_name='إرجاع للمستودع')),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='تاريخ المرتجع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='core.order', verbose_name='الأوردر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='المادة/المنتج')),
            ],
            options={
                'verbose_name': 'مرتجع',
                'verbose_name_plural': 'المرتجعات',
                'ordering': ['-date'],
            },
        ),
    ]
