# Generated by Django 5.0.6 on 2026-07-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_order_status_inventorymovement_returnrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('cliq', 'كليك'), ('bank', 'تحويل بنكي'), ('card', 'بطاقة/فيزا'), ('delivery', 'شركة التوصيل'), ('wallet', 'محفظة إلكترونية'), ('other', 'أخرى')], default='cash', max_length=30, verbose_name='طريقة الدفع'),
        ),
    ]
